sudo: required

language: python
python:
  - "3.8"
  - "3.9"

services:
  - docker

install:
  - pip3 install -r requirements.txt

script:
  - docker build -t test_build .
  - docker run test_build python3 /usr/src/ff_bot/setup.py test

env:
  - BOT_ID=916ccfd76a7fda25c74d09e1d5 LEAGUE_ID=164483
