sudo: required

language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"

services:
  - docker

install:
  - pip3 install flake8
  - docker build -t wilson .
  - docker run wilson python3 /usr/src/ff_bot/setup.py test

script: 
  - flake8 .
