name: Run tests on PRs and commits

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  BOT_ID: 916ccfd76a7fda25c74d09e1d5
  LEAGUE_ID: 164483

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Build container
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: false
      #     tags: test_build

      - run: docker build -t test_build .

      - name: Run image against tests
        run: docker run test_build python /usr/src/ff_bot/setup.py test
